// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform, debugPrint;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Helper function to safely get environment variables
  static String _getEnvVar(String key, String defaultValue) {
    try {
      // Check if dotenv is initialized before accessing it
      if (dotenv.isInitialized) {
        final String? value = dotenv.env[key];
        if (value != null && value.isNotEmpty) {
          return value;
        }
      }
      // Return default value if dotenv is not initialized or value is empty
      return defaultValue;
    } catch (e) {
      // If dotenv is not initialized or any error occurs, return the default value
      debugPrint('⚠️ تحذير: فشل في قراءة متغير البيئة $key: $e');
      return defaultValue;
    }
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _getEnvVar(
            'FIREBASE_WEB_API_KEY', 'AIzaSyDP_NoMRbRz5L7i2tWjYvhKJdMGQFJ7Dhk'),
        appId: _getEnvVar(
            'FIREBASE_WEB_APP_ID', '1:896287167731:web:3e8d157f5b83a508185386'),
        messagingSenderId:
            _getEnvVar('FIREBASE_WEB_MESSAGING_SENDER_ID', '896287167731'),
        projectId: _getEnvVar('FIREBASE_WEB_PROJECT_ID', 'samir-28c3e'),
        authDomain: _getEnvVar(
            'FIREBASE_WEB_AUTH_DOMAIN', 'samir-28c3e.firebaseapp.com'),
        databaseURL: _getEnvVar('FIREBASE_WEB_DATABASE_URL',
            'https://samir-28c3e-default-rtdb.firebaseio.com'),
        storageBucket: _getEnvVar(
            'FIREBASE_WEB_STORAGE_BUCKET', 'samir-28c3e.appspot.com'),
        measurementId:
            _getEnvVar('FIREBASE_WEB_MEASUREMENT_ID', 'G-W0FEYH3B02'),
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _getEnvVar('FIREBASE_ANDROID_API_KEY',
            'AIzaSyBNwxHAtnM-n1918PGK4Nzme4KlcnIRgyc'),
        appId: _getEnvVar('FIREBASE_ANDROID_APP_ID',
            '1:896287167731:android:eb69aca05bfefb2f185386'),
        messagingSenderId:
            _getEnvVar('FIREBASE_ANDROID_MESSAGING_SENDER_ID', '896287167731'),
        projectId: _getEnvVar('FIREBASE_ANDROID_PROJECT_ID', 'samir-28c3e'),
        databaseURL: _getEnvVar('FIREBASE_ANDROID_DATABASE_URL',
            'https://samir-28c3e-default-rtdb.firebaseio.com'),
        storageBucket: _getEnvVar(
            'FIREBASE_ANDROID_STORAGE_BUCKET', 'samir-28c3e.appspot.com'),
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _getEnvVar(
            'FIREBASE_IOS_API_KEY', 'AIzaSyBXodcxUcMTMDjyTUDzNDNZAorF_TWhxmw'),
        appId: _getEnvVar(
            'FIREBASE_IOS_APP_ID', '1:896287167731:ios:980cecf7930d0b95185386'),
        messagingSenderId:
            _getEnvVar('FIREBASE_IOS_MESSAGING_SENDER_ID', '896287167731'),
        projectId: _getEnvVar('FIREBASE_IOS_PROJECT_ID', 'samir-28c3e'),
        databaseURL: _getEnvVar('FIREBASE_IOS_DATABASE_URL',
            'https://samir-28c3e-default-rtdb.firebaseio.com'),
        storageBucket: _getEnvVar(
            'FIREBASE_IOS_STORAGE_BUCKET', 'samir-28c3e.appspot.com'),
        iosClientId: _getEnvVar('FIREBASE_IOS_CLIENT_ID',
            '896287167731-j07a2u7hiri9655eu7bbrpoudctgkagb.apps.googleusercontent.com'),
        iosBundleId: _getEnvVar(
            'FIREBASE_IOS_BUNDLE_ID', 'com.example.flutterApplicationOo'),
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: _getEnvVar('FIREBASE_MACOS_API_KEY',
            'AIzaSyBXodcxUcMTMDjyTUDzNDNZAorF_TWhxmw'),
        appId: _getEnvVar('FIREBASE_MACOS_APP_ID',
            '1:896287167731:ios:980cecf7930d0b95185386'),
        messagingSenderId:
            _getEnvVar('FIREBASE_MACOS_MESSAGING_SENDER_ID', '896287167731'),
        projectId: _getEnvVar('FIREBASE_MACOS_PROJECT_ID', 'samir-28c3e'),
        databaseURL: _getEnvVar('FIREBASE_MACOS_DATABASE_URL',
            'https://samir-28c3e-default-rtdb.firebaseio.com'),
        storageBucket: _getEnvVar(
            'FIREBASE_MACOS_STORAGE_BUCKET', 'samir-28c3e.appspot.com'),
        iosClientId: _getEnvVar('FIREBASE_MACOS_CLIENT_ID',
            '896287167731-j07a2u7hiri9655eu7bbrpoudctgkagb.apps.googleusercontent.com'),
        iosBundleId: _getEnvVar(
            'FIREBASE_MACOS_BUNDLE_ID', 'com.example.flutterApplicationOo'),
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: _getEnvVar('FIREBASE_WINDOWS_API_KEY',
            'AIzaSyDP_NoMRbRz5L7i2tWjYvhKJdMGQFJ7Dhk'),
        appId: _getEnvVar('FIREBASE_WINDOWS_APP_ID',
            '1:896287167731:web:f37124af8c82131c185386'),
        messagingSenderId:
            _getEnvVar('FIREBASE_WINDOWS_MESSAGING_SENDER_ID', '896287167731'),
        projectId: _getEnvVar('FIREBASE_WINDOWS_PROJECT_ID', 'samir-28c3e'),
        authDomain: _getEnvVar(
            'FIREBASE_WINDOWS_AUTH_DOMAIN', 'samir-28c3e.firebaseapp.com'),
        databaseURL: _getEnvVar('FIREBASE_WINDOWS_DATABASE_URL',
            'https://samir-28c3e-default-rtdb.firebaseio.com'),
        storageBucket: _getEnvVar(
            'FIREBASE_WINDOWS_STORAGE_BUCKET', 'samir-28c3e.appspot.com'),
        measurementId:
            _getEnvVar('FIREBASE_WINDOWS_MEASUREMENT_ID', 'G-5FYG14BQNT'),
      );
}
